name: CI Pipeline
run-name: ci-pipeline

on:
  push:
    branches: 
  pull_request:
    branches: [main]

jobs:
    dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: |
                go mod tidy
                go mod download


    build:
        runs-on: ubuntu-latest
        needs: dependencies
        steps:
            - run: go build -v ./...

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - run: go test ./...